# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
