# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_privacypolicy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=models.TextField(),
        ),
    ]
